config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :new, :edit, :create, :show, :update] do
    resources :bookmarks, only: [:create]
  end

  resources :bookmarks, only: [:destroy]
  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :list_id, scope: [:movie_id, :list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo
  validates :name, uniqueness: true
  validates :name, presence: true
  validates :photo, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_movie, only: [:create]
  before_action :set_list, only: [:create]
  before_action :set_bookmark, only: [:destroy]
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  def destroy
    @bookmark.destroy!
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_movie
    @movie = Movie.find(params[:bookmark][:movie_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [ :show, :edit, :update, :destroy]
  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def edit; end

  def update
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/">
   <%= image_tag "banner.jpg", alt: "A cinema", width: 200 %>
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item">
        <%= link_to "New list" , new_list_path, class: "nav-link" %>
        
      </li>
    </ul>
  </div>
</div>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <div class="form-group"><%= f.input :name, class: "form-control" %></div>
   <%= f.input :photo, as: :file %>
   <%= f.submit({class: 'btn btn-primary'}) %>
<% end %>

app/views/lists/edit.html.erb
<%= render "form", list: @list %>

app/views/lists/index.html.erb
<div class="banner banner-index">
  <div class="container text-center ">
  
    <h1>Save any kind of movies</strong></h1>
    <p>Be creative!</p>
    
  </div>
</div>

<div class="container">
   <h2>My Lists</h2>
  <div class="row">
    <% @lists.each do |list| %>
    <div class="col-4 py-2">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path list.photo.key, height: 300, width: 400, crop: :fill %>) " >
            <%= link_to list.name, list_path(list), class: "white" %>
        </div>
    </div>
   <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= render "form", list: @list %>

app/views/lists/show.html.erb
 
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @list.photo.key, height: 600, width: 800 %>)">
  <div class="container text-center ">
    <h1><strong><%= @list.name %></strong></h1>

  </div>
</div>

<div class="container">
  <div class="row">
    <% @list.bookmarks.each do |bookmark| %>
    <div class="col-4 py-2">  
    <div class="card-trip">
        <img src="<%= bookmark.movie.poster_url  %>" />
        <div class="card-trip-infos">
            <div>
            <h2><%= "#{bookmark.movie.title} #{bookmark.movie.rating}" %> <i class="fas fa-star"></i></h2>
            <p><%= bookmark.movie.overview %></p>
        </div>
        <h2 class="card-trip-pricing"><%= link_to "Delete", bookmark_path(bookmark), method: :delete, class: 'link-delete'  %></h2>
        </div>
        
    </div>
    </div>
   <% end %>
</div>
</div>
<div class="row justify-content-center">
  <div class="col-4 ">
<h1>Add a bookmark</h1>
<%= simple_form_for([@list, @bookmark]) do |f| %>
     <%= f.input :comment %>
     <%= f.association :movie %>
     <%= f.submit "ajouter", class: 'btn btn-primary w-100' %>
<% end %>
</div>
</div>